[pytest]
testpaths = tests
asyncio_mode = strict
filterwarnings =
    ignore::DeprecationWarning:starlette.*
    ignore::PendingDeprecationWarning:starlette.*
    ignore:.*PyType_Spec with a metaclass.*:DeprecationWarning
